import ExcelJS from "exceljs";
import { toISODate } from "./dates";
import type { Cell, Report, ReportColumn } from "./reports";

/** Spreadsheet formula-injection guard: text starting with = + - @ (or control chars) is prefixed with an apostrophe. */
export function safeCsvText(s: string): string {
  return /^[=+\-@\t\r]/.test(s) ? `'${s}` : s;
}

function csvCell(v: Cell, col: ReportColumn): string {
  if (v === null || v === undefined || v === "") return "";
  let s: string;
  if (v instanceof Date) s = toISODate(v);
  else if (typeof v === "number") s = col.type === "money" ? v.toFixed(2) : String(v);
  else s = safeCsvText(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function reportToCsv(r: Report): string {
  const head = r.columns.map((c) => csvCell(c.header, { ...c, type: "text" })).join(",");
  const lines = r.rows.map((row) => r.columns.map((c) => csvCell(row[c.key] ?? null, c)).join(","));
  return "﻿" + [head, ...lines].join("\r\n") + "\r\n";
}

export async function reportToXlsx(r: Report, meta: { subtitle: string; generatedBy: string; filters: Record<string, string> }): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "GST Reconciliation Tracker";
  wb.created = new Date();
  const ws = wb.addWorksheet(r.title.slice(0, 31), { views: [{ state: "frozen", ySplit: 1 }] });
  ws.columns = r.columns.map((c) => ({ header: c.header, key: c.key, width: c.width ?? 14 }));
  const head = ws.getRow(1);
  head.font = { bold: true, color: { argb: "FFFFFFFF" } };
  head.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E3A8A" } };
  head.alignment = { vertical: "middle", wrapText: true };
  head.height = 30;
  for (const row of r.rows) ws.addRow(row);
  r.columns.forEach((c, i) => {
    const col = ws.getColumn(i + 1);
    if (c.type === "money") col.numFmt = "#,##0.00;[Red]-#,##0.00";
    else if (c.type === "date") col.numFmt = "dd-mmm-yyyy";
    else if (c.type === "percent") col.numFmt = '0"%"';
    if (c.type === "money" || c.type === "int" || c.type === "percent") col.alignment = { horizontal: "right" };
  });
  ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: r.columns.length } };

  const info = wb.addWorksheet("About this export");
  info.addRow(["Report", r.title]);
  info.addRow(["Scope", meta.subtitle || "All periods"]);
  info.addRow(["Generated", new Date().toISOString()]);
  info.addRow(["Generated by", meta.generatedBy]);
  info.addRow(["Rows", r.rows.length + (r.truncated ? " (truncated – narrow the filters)" : "")]);
  for (const [k, v] of Object.entries(meta.filters)) info.addRow([`Filter: ${k}`, v]);
  info.getColumn(1).width = 24;
  info.getColumn(2).width = 60;
  info.getColumn(1).font = { bold: true };
  return Buffer.from(await wb.xlsx.writeBuffer());
}
